# Generated by Django 5.2.7 on 2025-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('support', 'Support Team')], max_length=50)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('bio', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
