# Generated by Django 5.2.7 on 2025-10-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gallerycategory_galleryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='title',
        ),
    ]
