# Generated by Django 5.2.7 on 2025-11-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_testimonial_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('popular', 'Popular'), ('online', 'Online'), ('special', 'Special Event'), ('intensive', 'Intensive'), ('regular', 'Regular')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('participants_limit', models.PositiveIntegerField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('is_free', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open for Registration'), ('closed', 'Closed'), ('invite', 'Invite Only'), ('early_bird', 'Early Bird Available'), ('completed', 'Completed')], max_length=50)),
                ('registration_open', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('goals', models.TextField(blank=True)),
                ('heard_about', models.CharField(blank=True, choices=[('social_media', 'Social Media'), ('email', 'Email Newsletter'), ('friend', 'Friend/Colleague'), ('website', 'Website'), ('other', 'Other')], max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('free', 'Free')], default='pending', max_length=20)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.event')),
            ],
        ),
    ]
