# Generated by Django 5.2.7 on 2025-11-05 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('focus', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('format', models.TextField(blank=True, null=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.programcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('team_size', models.CharField(blank=True, choices=[('1-5', '1-5 people'), ('5-10', '5-10 people'), ('10-20', '10-20 people'), ('20+', '20+ people')], max_length=10)),
                ('challenges', models.TextField(blank=True, help_text='Describe your current sales challenges and goals')),
                ('has_paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.program')),
            ],
        ),
    ]
