# Generated by Django 5.2.7 on 2025-11-10 13:38

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_programcategory_program_programfeature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-registration_date']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='programcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Program Categories'},
        ),
        migrations.AlterModelOptions(
            name='programfeature',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='programregistration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'email')},
        ),
        migrations.RemoveField(
            model_name='program',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='payment_reference',
        ),
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waiting_list', 'Waiting List')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(default=api.models.generate_unique_id, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='badge',
            field=models.CharField(blank=True, default='OpenBook', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='focus',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='format',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='outcome',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='programregistration',
            name='challenges',
            field=models.TextField(blank=True, help_text='Describe your current challenges and goals'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='logo',
            field=models.ImageField(upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='payment_status',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(choices=[('pesapal', 'PesaPal'), ('cash', 'Cash')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('pesapal_order_tracking_id', models.CharField(blank=True, max_length=50)),
                ('pesapal_transaction_id', models.CharField(blank=True, max_length=50)),
                ('pesapal_merchant_reference', models.CharField(blank=True, max_length=100)),
                ('pesapal_payment_url', models.URLField(blank=True)),
                ('payment_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.eventregistration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pesapal_order_tracking_id'], name='api_payment_pesapal_d80f9c_idx'), models.Index(fields=['payment_status'], name='api_payment_payment_1a5536_idx')],
            },
        ),
    ]
