# Generated by Django 5.2.7 on 2025-11-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pesapal_merchant_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pesapal_order_tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pesapal_payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pesapal_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
