# Generated by Django 5.2.7 on 2025-11-11 13:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_payment_pesapal_merchant_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(default=api.models.generate_unique_id, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
