# Generated by Django 5.2.7 on 2025-11-12 08:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.CharField(default=api.models.generate_unique_id, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
