# Generated by Django 5.2.7 on 2025-11-12 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_program_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(choices=[('pesapal', 'PesaPal'), ('cash', 'Cash')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('pesapal_order_tracking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pesapal_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pesapal_merchant_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('pesapal_payment_url', models.URLField(blank=True, null=True)),
                ('payment_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.programregistration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pesapal_order_tracking_id'], name='api_program_pesapal_53845d_idx'), models.Index(fields=['payment_status'], name='api_program_payment_9cf91e_idx')],
            },
        ),
    ]
